FROM tensorflow/tensorflow:1.14.0-py3

SHELL ["/bin/bash", "-c"]

RUN apt-get update && \
    apt-get install curl -y	

COPY requirements.txt

RUN pip install -q -r requirements.txt

ADD . /app

WORKDIR /app

EXPOSE 5000

CMD ["python", "src/app.py"]
